version: "3"

services:
  centos6:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-centos6
    environment:
      TZ: Asia/Tokyo
    command: tail -f /dev/null

  centos7:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-centos7
    environment:
      TZ: Asia/Tokyo
    command: tail -f /dev/null
