FROM centos:7.4.1708

RUN echo 'ZONE="Asia/Tokyo"' > /etc/sysconfig/clock
RUN rm -f /etc/localtime && \
    ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

RUN useradd -s /bin/bash -u 4096 -U cloudera-ps

RUN yum install -y sudo
RUN echo "cloudera-ps ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

WORKDIR /home/cloudera-ps

RUN yum install -y xz && \
    curl -L -s https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz | tar Jx && \
    chown -R cloudera-ps:cloudera-ps ./shellcheck-stable

RUN curl -L -s https://github.com/kward/shunit2/archive/v2.1.7.tar.gz | tar zx && \
    chown -R cloudera-ps:cloudera-ps ./shunit2-2.1.7

COPY --chown=cloudera-ps:cloudera-ps ./*.sh ./
COPY --chown=cloudera-ps:cloudera-ps ./lib ./lib
COPY --chown=cloudera-ps:cloudera-ps ./test ./test

USER cloudera-ps
